# FUNDAMENTAL OF IMAGE PROCESSING SECV3213
# SECTION 01
# TEAM MEMBERS:
# SITI NURUL AMIRAH BINTI SHEIKH SULAIMAN A23CS0182
# NUR AIFA INSYIRAH BINTI HAIRUL AZMI A23CS8005 
# RADEN SALMA HUMAIRA BINTI MUHAMMAD MUN'IM  A23CS0264

from ui.app import SnappicApp

if __name__ == "__main__":
    app = SnappicApp()
    app.mainloop()
